services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "python seed.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: ./zichan-manager-frontend
      target: deps
    ports:
      - "3000:5173"
    volumes:
      - ./zichan-manager-frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    env_file:
      - ./zichan-manager-frontend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - backend